---
services:
    frontend-app:
        container_name: humavery-frontend
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - APP_PORT=${APP_PORT:-3000}
        env_file:
            - .env
        ports:
            - "${APP_PORT:-3000}:3000"
