import type { Metadata } from "next"
import type { IChildren } from "../libs/models/components/general/interfaces/IChildren"
import type { JSX } from "react"
import { Geist } from "next/font/google"
import "@/humavery/styles/GlobalStyles.css"

/**
 * @summary The font for the website.
 * @description This is the font that will be used for the website.
 */
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

/**
 * @summary The metadata for the website.
 * @description This is the metadata for the website.
 */
const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

/**
 * @summary The root layout for the website.
 * @description This is the root layout for the website. It is the parent component for all pages.
 */
function RootLayout({ children }: IChildren): JSX.Element {
    return (
        <html lang="en" className={`${geistSans.variable} h-full antialiased`} suppressHydrationWarning>
            <body>
                {children}
            </body>
        </html>
    )
}

export { metadata }
export default RootLayout
