# Configuration of the CD workflow for the frontend application.
# Workflow is responsible for deploying the production build of the application to Vercel.
---
name: Deploy frontend application to Vercel.
on:
    workflow_run:
        workflows:
            - Validate frontend's application code quality & try to build the application.
        types:
            - completed
        branches:
            - main
permissions:
    contents: read
defaults:
    run:
        shell: bash
jobs:
    deploy-production:
        name: Deploy production build to Vercel.
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        env:
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

            NODE_ENV: production

            NEXT_PUBLIC_API_ENDPOINT_URL: https://api.humavery.com
            NEXT_PUBLIC_CDN_ENDPOINT_URL: https://cdn.humavery.com
            NEXT_PUBLIC_WEBSITE_ENDPOINT_URL: https://humavery.com

            # Every single environment variable needs to be set in order to make the application work correctly.

        steps:
            - name: Checkout repository at CI commit.
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.event.workflow_run.head_sha }}
            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install dependencies.
              run: |
                  bun install --frozen-lockfile
                  bun add -d vercel
            - name: Pull Vercel environment configuration.
              run: bunx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            - name: Build application for production.
              run: bunx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy prebuilt application to Vercel.
              run: bunx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
